<h1>¿Qué es NumPy</h1>

Es una libreria matematica que se usa para distintos procesos de estadistica o algebra, le añade mas tipos de datos y funcionalidades a python
como lo es los Arrays

In [1]:
import numpy as np

<h2>Arrays</h2>
Un array es el tipico array que se conoce pero numpy le da mas funcionalidad, como hacerlo de distintas dimensiones
<h3>Terminos importantes</h3>
- A cada dimension se le llama axis (rows) <br>
- El numero total de dimensiones (rows) se le dice ranks<br>
- Las dimensiones con su longitud (rows and columns) se le llama shape<br>
- El total de elementos que contiene el array se le llama size

In [4]:
array_ejemplo = np.zeros((2,3)) #El primer parametro son las rows el segundo las columns
print(array_ejemplo)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
array_ejemplo.shape

(2, 3)

In [7]:
array_ejemplo.ndim #te muestra las dimensiones del arreglo

2

In [8]:
array_ejemplo.size

6

<h3>Creacion de arrays</h3>

In [16]:
nuevo_array = np.empty((3,2,4)) #seria un arreglo con 3 niveles, cada nivel con 2 arreglos y cada arreglo con 4 elementos
print(nuevo_array)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [17]:
#Array a partir de una lista
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
#Array basado en rangos(inicio, final, cantidad de numeros)
b = np.linspace(1, 5, 10)
b

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [20]:
#Array con valores aleatorios
np.random.rand(2,4)

array([[0.58046091, 0.6031117 , 0.81440251, 0.82379819],
       [0.84767983, 0.837585  , 0.77223131, 0.39674699]])

In [21]:
#Array con valores aleatorios de acuerdo a una formula matematica
np.random.randn(2,4)

array([[-0.60770868,  0.33938979,  0.38355357,  2.03353974],
       [ 0.52284991, -0.72759696, -0.68744005,  0.12710474]])